### ISSUE TITLE
USER STORY: User registration

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#1]
As a **new site user** I can **create a new user account** so that **I can log into and use the full functionality of the site**

#  Acceptance Criteria
- a sign-up form is rendered on the site which may be filled in by the user
- once the form is submitted, the data is saved in a database
-  the user receives feedback on whether account creation was successful or not
- the user is automatically logged in following registration

# Tasks
- [x] create database for user data to be saved to
- [x] create User model
- [x] create log in page template with a rendered form
- [x] encrypt password before storage
- [x] add user to database on form submission
- [x] log in user and redirect to home page
- [x] return success/failure message to user
