### ISSUE TITLE
USER STORY: Other user profile - Interacting with other users

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#10]
As a **registered site user** I can **like and message other users** so that **I can interact with other users and discuss interests or projects**

#  Acceptance Criteria
- Users are able to like (or "star") other users
- Users are able to send messages to one another
- Users successfully receive messages from one another
- (could do) Users are notified when they have received a new message

# Tasks
- [ ] add "star" many to many table in database
- [ ] add starred user to a "starred" list and display to user (for easily finding users later)
- [x] add "messages" many to many table in database
- [x] add functionality for users to send messages to eachother
- [x] add functionality for users to receive messages from eachother
- [ ] (could do) show user who has starred them
- [ ] (could do) show notifications when new messages are received

**Comment by dragon-fire-fly** [comment]
Closed as the remaining tasks will not be implemented in this iteration
