### ISSUE TITLE
USER STORY: Project - Interacting with projects

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#11]
As a **registered site user** I can **star and add comments to projects** so that **I can interact with projects, share my ideas and contact the project owner**

#  Acceptance Criteria
- The user can star projects to be able to easily find them later
- The user can comment on projects to share ideas, give tips, etc.
- The user can contact the project owner directly to ask for more details or ask to be added to the project

# Tasks
- [x] add many-to-many table for projects
- [ ] add option for user to like (or "star") projects
- [ ] add option for users to add comments to project pages
- [x] add option for user to message project owner directly

**Comment by dragon-fire-fly** [comment]
Closed as the remaining tasks will not be implemented in this iteration
