### ISSUE TITLE
USER STORY: Basic user sign-in

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#2]
As a **registered user** I can **log in to my user account** so that **I can access full functionality of the site**

#  Acceptance Criteria
- Sign-in form renders correctly on sign in page
- Correctly entered credentials lead to successful log in
- Log in is acknowledged with a welcome message

# Tasks
- [x] Check entered credentials against those stored in the database
- [x] Determine whether user is authenticated or not
- [x] Show whether user is logged in or not
- [x]  Allow access to restricted areas of the site (to an appropriate security level)
