### ISSUE TITLE
USER STORY: View, edit and delete user profiles

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#3]
As a **registered user** I can **view, update and delete my profile** so that **I can amend and delete my data**

#  Acceptance Criteria
- User is able to access and edit their own account details using a form
- User can delete their own user account (confirmation before deletion would be good)
- Deleted users are logged out and no longer able to access the restricted areas of the site

# Tasks
- [x] create user edit view with a form and template
- [x] successfully update edited user profile in database and return updated data to profile
- [x] redirect to profile page once editing is completed
- [x] delete data from the database if user selects delete profile option
- [x] check with user if they definitely want to delete their profile (modal)
- [x] log user out once they have deleted their account
