### ISSUE TITLE
USER STORY: Log in with google account

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#4]
As a **google account holder** I can **log in with my Gmail account** so that **I do not have to manually enter my details or create a password when signing up to the site**

#  Acceptance Criteria
- Users see a button to log in using their Google credentials
- Users can log in using their Google credentials
- A new user account is created using the Google credentials obtained through the Google log in
- Users accessing the site through a Google account have the same functionality as regular users

# Tasks
- [ ] Obtain a Google client ID and secret key
- [ ] Updates settings.py with google account login requirements through Allauth
- [ ] Add google log in button to log in page
- [ ] Configure google log in redirect through Allauth
