### ISSUE TITLE
USER STORY: Project View, Edit and Delete Functions

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#40]
As a **project owner** I can **edit and delete my own projects** so that **I can update the details or remove the project form the site**

#  Acceptance Criteria

- [x] Only the project owner (and admins) can edit or delete projects
- [x] The project details can (only) be edited by the project owner
- [x] The project can (only) be deleted by the project owner
- [x] The user must confirm they want to delete a project

# Tasks
- [x] Add edit and delete buttons
- [x] Add edit form and template and process the form in views
- [x] Add authentication so only project owners can edit or delete specific projects
- [x] Add modal for project deletion confirmation
- [x] Add messages to display success and validation errors to user
- [x] Restrict edit and delete functions to project owner
