### ISSUE TITLE
USER STORY: Adding and removing project images

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#42]
As a **project owner** I can **add and remove images for my project** so that **other users can get a visual idea of the project**

#  Acceptance Criteria

- [x] Project owner can upload pictures for their project
- [x] Project owner can delete pictures
- [ ] Project owner is asked to confirm they want to delete (should-do)
- [x] Only project owners can add and remove pictures
- [x] Pictures are displayed on the project page

# Tasks
- [x] Add a image upload form
- [x] Add a delete image button for each image
- [x] Display added images on the project overview page
- [x] Restrict access for editing to project owners and admin users
