### ISSUE TITLE
USER STORY: Other user profiles overview

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#5]
As a **registered user** I can **see an overview of other users on the site** so that **I can get an overview of the skills, interests and projects of other users**

#  Acceptance Criteria
- The "Find Developers" page successfully loads an overview of the other users on the site
- Each profile shows the user's profile picture (if present), username and programming languages
- Clicking on an individual profile takes the user to that specific user's page

# Tasks
- [x] Create "Find Developers" template and link up views, urls, etc.
- [x] Access relevant fields of each user profile and display for each user 
- [x] Link each user profile to their detailed profile view
- [x] Unittests
