### ISSUE TITLE
USER STORY: Other user profile - detailed view

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#6]
As a **registered user** I can **view the profiles of other users** so that **I can see whether this user is interesting to me based on my interests, programming languages, current projects, etc.**

#  Acceptance Criteria
- The profile of the selected user is rendered to the browser
- The relevant user data is obtained from the database and sent to the template through the view
- The user has the ability to interact with the other user (via messaging etc.)

# Tasks
- [x] access specific data for the specific user from the database
- [x] create a view to return the relevant data
- [x] style the template, showing the relevant data for the selected user (excluding any sensitive data such as email or password)
- [x] unittests
