### ISSUE TITLE
USER STORY: Accessibility

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#66]
As a **disabled site user** my **accessibility needs have been addressed** so that I can **fully perceive, understand, navigate, and interact with all aspects of the website**

#  Acceptance Criteria
- Colour combinations used or background/text should be AA or above
- WAVE accessibility tool should not detect any errors

# Tasks
- [x] Test contrast of different colour combinations using EightShapes contrast grid (https://contrast-grid.eightshapes.com/) and make changes as appropriate
- [x] Test with WAVE accessibility tool (https://wave.webaim.org/) and fix any highlighted problems
- [x] Ensure that all images have alt texts and links that only show icons have aria-labels.
