### ISSUE TITLE
USER STORY: Update and delete messages

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#68]
As the **sender of a message** I can **edit my message** so that **I can change its contents** and as both a **sender and receiver** of a message I can **delete a message** so that I can remove it from my account

#  Acceptance Criteria
- Only the user who sent a message may edit it
- Both the sender and the recipient may delete a selected message
- The edit and delete functions should be available on both the inbox/outbox pages and the individual message pages

# Tasks
- [x] Implement an edit message function
- [x] Implement a delete message function
- [x] Make both available on the inbox/outbox page
- [x] Make both available on the individual message pages
- [x] Only the message sender may edit a message.
