### ISSUE TITLE
USER STORY: Search and sort functionality - Users

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#7]
As a **registered site user** I can **perform a search for other users based on a variety of parameters** so that **I can more easily find the type of user I am looking for**

#  Acceptance Criteria
- A search bar is present on the "Find Developers" page
- Users can filter other users by various criteria - e.g. programming language, location, projects
- Users can sort search results by various criteria - e.g. alphabetically

# Tasks
- [ ] ~~add a search bar to the "Find Developers" page~~
- [ ] ~~perform search and limit the displayed profiles based on search criteria~~
- [x] add sorting functionality for displayed results

**Comment by dragon-fire-fly** [comment]
This user story has been marked as closed as a filtering functionality was implemented, but searching or filtering by other criteria were deemed to be unimportant for the MVP. They could be implemented in the next iteration, if deemed important.
