### ISSUE TITLE
USER STORY: Project overview

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#8]
As a **registered user** I can **see an overview of all the active projects posted on the site** so that **I can read details about the projects and decide which are potentially of interest to me**

#  Acceptance Criteria
- The "Find Projects" page successfully loads an overview of the active projects on the site
- Each project shows the project thumbnail (if present), username of the project host, programming languages sought and a short summary
- Clicking on an individual project takes the user to that specific project page

# Tasks
- [x] Create "Find Projects" template and link up views, urls, etc.
- [x] Access relevant fields of each project and display the info for each on the summary page
- [x] Link each project to the detailed view of that project
- [x] unittests
