### ISSUE TITLE
USER STORY: Project - detailed view

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/developer_matcher#9]
As a **registered site user** I can **view the details of active projects** so that **I can assess if the project is of interest to me, if my skills and experience are suitable for the project and contact the project owner**

#  Acceptance Criteria
- The details of a specific project is rendered to the browser
- The relevant project data is obtained from the database and sent to the template through the view

# Tasks
- [x] access specific data for the relevant project from the database
- [x] create a view to return the relevant data
- [x] style the template, showing the relevant data for the project
